declare var require: any;
export const environment = {
  name: 'ghpages',
  email: 'info@mk.pl',
  version: require('../../package.json').version,
  production: true,
  backendDelay: 0,
  httpRetry: 0,
  autoLogOutTimeout: 5,
  loggingBackendUrl: true,
  loggingBackendRequestHeaders: false,
  loggingBackendRequest: false,
  loggingBackendResponse: false,
  apiEndpoint: '/api',
  messageDismissible: false,
  messageSuccessTimeout: 1000 * 10,
  messageInfoTimeout: 1000 * 20,
  messageAnotherTimeout: 1000 * 60,
  allowedDomains: ["localhost"],
  disallowedRoutes: [],
  urlContact: '#',
  urlBlog: '#',
  urlRegulation: '#',
  urlPolicy: '#'
};
