declare var require: any;
export const environment = {
  name: 'dev',
  email: 'info@martynaklewinowska.pl',
  version: require('../../package.json').version,
  production: false,
  backendDelay: 50,
  httpRetry: 0,
  autoLogOutTimeout: 20,
  loggingBackendUrl: true,
  loggingBackendRequestHeaders: false,
  loggingBackendRequest: false,
  loggingBackendResponse: false,
  apiEndpoint: '/api',
  messageDismissible: false,
  messageSuccessTimeout: 1000 * 10,
  messageInfoTimeout: 1000 * 20,
  messageAnotherTimeout: 1000 * 60,
  allowedDomains: ['localhost'],
  disallowedRoutes: [],
  urlContact: 'http://www.martynaklewinowska.pl/kontakt',
  urlBlog: 'http://www.martynaklewinowska.pl/blog',
  urlRegulation: 'https://sklep.martynaklewinowska.pl/resource/sklep.regulamin.pdf',
  urlPolicy: 'https://sklep.martynaklewinowska.pl/resource/sklep.polityka.prywatnosci.pdf',
  urlFacebook: 'https://www.facebook.com/martynaklewinowska',
  urlInstagram: 'https://www.instagram.com/martynaklewinowska/'
};
